import type { Metadata } from "next";
import Link from "next/link";
import { getAllCategories, getSettings } from "@/lib/blog";
import { SUBMISSION_LIMITS } from "@/lib/constants";
import { categoryHref } from "@/lib/routes";
import { siteConfig } from "@/config/site";
import { breadcrumbJsonLd, buildMetadata, JsonLd } from "@/lib/seo";
import { ProsePage } from "@/components/layout/ProsePage";
import { Button } from "@/components/ui/Button";
import { PenIcon } from "@/components/ui/Icons";

export const metadata: Metadata = buildMetadata({
  title: "Write for Us",
  description: `Write for ${siteConfig.name}. Read our contributor guidelines, accepted topics, article requirements and editorial review process, then submit your original article.`,
  path: "/write-for-us",
});

export default async function WriteForUsPage() {
  const [categories, settings] = await Promise.all([getAllCategories(), getSettings()]);
  return (
    <ProsePage
      title="Write for Us"
      kicker="Contributors"
      intro={`${siteConfig.name} welcomes original articles from writers who know their subject. If you can teach our readers something useful, we would like to read your work.`}
    >
      <JsonLd data={breadcrumbJsonLd([{ name: "Home", path: "/" }, { name: "Write for Us", path: "/write-for-us" }])} />

      <p>
        We publish articles across {categories.length} categories. Every contributor article goes through editorial review, and nothing is published until an editor approves it. Please read the guidelines below before you submit.
      </p>
      <p className="!mt-6 flex flex-wrap gap-3 not-prose">
        <Button href="/submit" icon={<PenIcon size={16} />} iconPosition="start" className="!text-white !no-underline">Submit an article</Button>
      </p>

      <h2>Topics we accept</h2>
      <p>We accept articles that fit one of these categories:</p>
      <ul>
        {categories.map((category) => (
          <li key={category.slug}>
            <Link href={categoryHref(category.slug)}>{category.name}</Link>: {category.topics.slice(0, 4).join(", ")}
          </li>
        ))}
      </ul>

      <h2 id="guidelines">Submission guidelines</h2>
      <ul>
        <li><strong>Original content:</strong> Your article must be your own work and must not be published anywhere else, including your own blog. It must not be submitted to another publication at the same time.</li>
        <li><strong>Useful and specific:</strong> Teach readers something, share real experience or make a clear argument. Practical examples are better than general advice.</li>
        <li><strong>Length:</strong> We need at least {SUBMISSION_LIMITS.minWords} words. Most accepted articles run between 800 and 2,000 words.</li>
        <li><strong>Structure:</strong> Use a clear introduction, descriptive headings and subheadings, short paragraphs and lists where they help. Our editor includes ready-made templates.</li>
        <li><strong>Accuracy:</strong> Support facts and figures with credible sources and link to them where it helps the reader.</li>
        <li><strong>Images:</strong> Add a featured image and include alt text for every image. You must own the image or have the right to use it. JPG, PNG or WebP up to 4 MB each.</li>
        <li><strong>Tone:</strong> Write for readers, not for search engines. Do not stuff keywords or repeat the same phrase unnaturally.</li>
        <li><strong>Editorial rights:</strong> Our editors may edit your article for clarity, length and style, and may decline it if it does not meet our standards.</li>
      </ul>

      <h2>Links and promotion</h2>
      <ul>
        <li>Articles must not promote a product, service, brand or website.</li>
        <li>Link only to credible sources that help the reader. Do not include paid, affiliate or irrelevant links.</li>
        <li>Your website or profile may appear in your author bio and is marked so that it does not pass search ranking credit.</li>
      </ul>

      <h2>What we do not accept</h2>
      <ul>
        <li>Spam, advertorials, sponsored posts or articles written mainly to place a backlink.</li>
        <li>Content copied, spun or lightly rewritten from other sources, or text generated by AI without substantial human work and review.</li>
        <li>Articles that are thin, repetitive or unrelated to our categories.</li>
        <li>Illegal, hateful, adult, gambling, or misleading health and financial content.</li>
      </ul>

      <h2>Benefits for contributors</h2>
      <ul>
        <li>A byline and author bio on every article you publish with us.</li>
        <li>A link to your own website or profile in your bio.</li>
        <li>Editorial feedback from our team before publication.</li>
        <li>A clean, readable page for your work that is shared with our readers across categories.</li>
      </ul>

      <h2>How to submit</h2>
      <ol>
        <li>Open the <Link href="/submit">submission editor</Link> and write your article. Your draft saves automatically in your browser.</li>
        <li>Add your title, short description, category, tags and featured image.</li>
        <li>Add your name, email address and a short bio of up to {SUBMISSION_LIMITS.bioMax} characters. Your email is only seen by our editors and is never published.</li>
        <li>Submit the article for review. You receive a submission ID.</li>
      </ol>

      <h2>The review process</h2>
      <p>
        An editor reads each submission, checks it against our <Link href="/about#standards">editorial standards</Link> and decides whether to approve it, ask for changes or decline it. We aim to respond within 5 to 7 working days, but we cannot guarantee publication. Approved articles are published under your byline with your short bio.
      </p>

      <h2>Questions</h2>
      <p>
        If you have a question before you write, email <a href={`mailto:${settings.contributorEmail}`}>{settings.contributorEmail}</a>.
      </p>
    </ProsePage>
  );
}
